category: 'AH5_CD'
description: 'AH5_DESC'
# Commented start_date and end_date means they will be calculated
# automatically as end = date of last Saturday,
# start =  end - 14 months
# Uncomment start_date and end_date in order to set them manually
start: '2021-09-01'
end: '2022-10-22'
seasonality: 5
high_spend: 500000
