paths:
  MBR_EXTENDED: "s3://memberanalytics-data-out-prod/pipelined_intermediates/master/member_extended"
  DETAILS: "s3://memberanalytics-data-out-prod/pipelined_intermediates/transaction_fiscal/detail/"
  PAYMENTS: "s3://memberanalytics-data-out-prod/pipelined_intermediates/transaction_fiscal/payment"
  BBM_SCORE: "s3://memberanalytics-data-out-prod/MODELDATA/BBM_PROPENSITY/BBM_SCORES/BBM SCORED MU FILE 2019-11-09.csv"
  BBM_SUMMARY_OUTPUT: "s3://memberanalytics-data-out-prod/MODELDATA/PREDICTIONS/BBM_PROPENSITY/QC/DECILE_SUMMARY/"
covariate_shift_lag: # list of lag(weeks) we would like to compare the current score to
  - 1
  - 4
bbm_score_lag: 9 # how far back (in weeks) was the BBM propensity model scored which we want to check for accuracy?
coupon_window: 21 # how many days the bbm coupon window is
coupons: # list of BBM coupon types we are interested in
  - ZPAP
  - ZCOU
