import logging
import os
import unittest

import findspark
from pyspark import SparkContext, SparkConf
from pyspark.sql import SparkSession
import xmlrunner
import yaml

from pe_memberdna.testing_support.lib.utility import (
    copy_local_to_s3,
    remove_from_s3,
    get_unique_id,
)


def prepare_etl_data(spark_in, unittest_config_path):
    """
    Copy the local text files from test_data/ETL/
    to an S3 folder that simulates the memberdna-data-in
    bucket.

    Args:
        spark_in - spark object
    """

    with open(unittest_config_path) as config_file:
        unittest_config = yaml.load(config_file, Loader=yaml.FullLoader)

    for file_path_in in unittest_config["local_test_file_names"]:

        copy_local_to_s3(
            os.path.join(
                os.path.abspath(os.path.dirname(__file__)),
                "data/" + file_path_in,
            ),
            unittest_config["s3_in_path"] + file_path_in,
        )

    df = spark_in.read.csv(
        unittest_config["s3_in_path"] + "CATEGORY_DNA_full.txt",
        sep="|",
        header=True,
        quote='"',
    )

    df.write.parquet(
        unittest_config["s3_in_path"] + "CATEGORY_DNA_full/PARQUET/",
        mode="overwrite",
    )


def run_etl(simulated_config_path):
    """
    Execute the source ETL, check the functionality of etl/run.py
    """

    class ArgsClass(object):
        """
        Mock args produced by parser
        """

        def __init__(self):
            self.config_path = simulated_config_path
            self.single_task = None

    args = ArgsClass()

    config = load_config(args)
    main(config)


class TestIfSourceEtlRuns(unittest.TestCase):
    """
    Test that source ETL runs without errors
    """

    @classmethod
    def setUpClass(cls):
        """
        Prepare the raw source data into an S3 folder
        """
        test_name = cls.__name__
        unique_id = get_unique_id(test_name)

        cls.unittest_config_path = os.path.join(
            os.path.abspath(os.path.dirname(__file__)),
            "data/unittest_config.yaml.{}".format(unique_id),
        )

        cls.simulated_config_path = os.path.join(
            os.path.abspath(os.path.dirname(__file__)),
            "data/simulated_config.yaml.{}".format(unique_id),
        )

        templates = [
            cls.simulated_config_path,
            cls.unittest_config_path,
        ]
        for template in templates:
            original = template.replace(".{}".format(unique_id), "")
            with open(original, "r") as config_file:
                config = config_file.read()
            with open(template, "w") as config_file:
                config = config.replace("UNIQUE_ID", unique_id)
                config_file.write(config)

        prepare_etl_data(spark, cls.unittest_config_path)

    # This test is failing because of PYTHONPATH conflict.
    def test_etl_pass(self):
        """
        Run the source ETL on the test data
        """
        run_etl(self.simulated_config_path)

    @classmethod
    def tearDownClass(cls):
        """
        Delete the S3 files generated by this test
        """
        with open(cls.unittest_config_path) as config_file:
            unittest_config = yaml.load(config_file, Loader=yaml.FullLoader)

        remove_from_s3(unittest_config["root_s3_path"])


if __name__ == "__main__":

    findspark.init()
    name = "Source ETL - unittests"

    conf = SparkConf().setAppName(name)
    sc = SparkContext(conf=conf)
    spark = SparkSession.builder.getOrCreate()
    spark.sparkContext.setLogLevel("WARN")
    logging.getLogger().setLevel(logging.INFO)
    unittest.main(
        testRunner=xmlrunner.XMLTestRunner(output="unit-test-reports"),
        # these make sure that some options that are not applicable
        # remain hidden from the help menu.
        failfast=False,
        buffer=False,
        catchbreak=False,
    )
