paths:
      # bucket is prepended to all paths, except to the ones that
      # already begin with s3://...
      output_prefix: 'ref'
      
      bucket: "memberanalytics-data-out-prod"

      input:
            # dir is not prepended to s3_stat_path
            s3_stat_path: "v2/stage/{output_prefix}/STATS/DNA/latest_stats.yaml"

            # dir is prepended to all paths
            dir: "v2/stage/{output_prefix}/pipelined_intermediates"

            skeleton_path: "skeleton"

            header_path: 'transaction_fiscal/header'
            detail_path: 'transaction_fiscal/detail'
            payment_path: 'transaction_fiscal/payment'
            detail_isnr_path: 'transaction_fiscal/detail_isnr'
            member_path: 'master/member'
            member_extended_path: "master/member_extended"
            member_history_path: 'master/member_history'
            census_tract_path: 'master/census_tract'
            club_path: 'master/club_with_brand'
            coupon_clip_path: 'coupon_clip_fiscal/'
            segment_path: 'bcg_maps/strategic_segment/Strategic_Segments.csv'

            email_path : 'master/email'
            email_fiscal_path: 'master/email_fiscal'
            awards_fiscal_path: 'awards_fiscal'

            tender_map_path: 'bcg_maps/tender_type_group_csv'

            quotient_id_path: 'quotient_id'

            # TODO: correct spelling in path
            AH5_custumer_facing_desc_path: 'bcg_maps/AH5_custumer_facing_desc/AH5_custumer_facing_desc.csv'

            acq_dna_path: "s3://memberanalytics-data-out-prod/v2/dev/acq/member_dna/recent/"
            mbr_basic_path: "s3://memberanalytics-data-in-prod/dev/Membership/PE_Membership_Mstr_YYYYmmdd.csv"

      output:
            # dir is not prepended to s3_stat_path
            s3_stat_path: "v2/stage/{output_prefix}/STATS/DNA/latest_stats.yaml"

            # dir is prepended to all paths
            dir: "v2/stage/{output_prefix}/CUBES"

            coupon_and_digital_1_path: "intermediates/coupon_and_digital_1"
            coupon_and_digital_2_path: "intermediates/coupon_and_digital_2"
            member_features_path: "intermediates/member"
            transaction_1_path: "intermediates/transaction_1"
            transaction_2_path: "intermediates/transaction_2"
            transaction_3_path: "intermediates/transaction_3"
            most_shopped_path: "intermediates/most_shopped"
            misc_path: "intermediates/misc"
            acquisition_path: "intermediates/acquisition"

            dna_path: "customer_cube_full/customer_cube"
            archive_base_path: ""

params:
      # Commented start_date and end_date means they will be calculated
      # automatically as end_date = date of last Saturday,
      # start_date =  end_date - 14 months
      # Uncomment start_date and end_date in order to set them manually
      # start_date: "2018-02-01" # (end_date - start_date) should be ~ 14 months
      # end_date: "2019-04-06"
      archive: True

validation: