paths:
      TRANSACTIONS_PATH: s3://memberanalytics-data-out-prod/REGRESSION_TESTS/assignment/Backfill/pipelined_intermediates/transaction_fiscal/detail3
      ARTICLE_DNA_PATH: s3://memberanalytics-data-out-prod/REGRESSION_TESTS/assignment/Backfill/CATEGORY_DNA/PROD/ARTICLE_NBR/CATEGORY_DNA_full/PARQUET
      AH5_DNA_PATH: s3://memberanalytics-data-out-prod/REGRESSION_TESTS/assignment/Backfill/CATEGORY_DNA/PROD/AH5_CD/CATEGORY_DNA_full/PARQUET
      AH4_DNA_PATH: s3://memberanalytics-data-out-prod/REGRESSION_TESTS/assignment/Backfill/CATEGORY_DNA/PROD/AH4_CD/CATEGORY_DNA_full/PARQUET
      ARTICLE_AH4_AH5_MAP: s3://memberanalytics-data-out-prod/REGRESSION_TESTS/assignment/Backfill/pipelined_intermediates/master/item
      RAW_MEMBER: s3://memberanalytics-data-out-prod/REGRESSION_TESTS/assignment/Backfill/pipelined_intermediates/master/member_extended
      ITEM_MASTER: s3://memberanalytics-data-out-prod/REGRESSION_TESTS/assignment/Backfill/pipelined_intermediates/master/item
      CDSA_LOC: s3://memberanalytics-data-out-prod/REGRESSION_TESTS/assignment/Backfill/ASSIGNMENTS/cdsa/
      ASSN_LOC: s3://memberanalytics-data-out-prod/REGRESSION_TESTS/assignment/Backfill/ASSIGNMENTS/cdsa/assn_output/
      LOG_LOC: s3://memberanalytics-data-out-prod/REGRESSION_TESTS/assignment/Backfill/ASSIGNMENTS/logs/
      CUBE: s3://memberanalytics-data-out-prod/REGRESSION_TESTS/assignment/Backfill/CUBES/customer_cube_2019-01-07/customer_cube
      PROPENSITY: s3://memberanalytics-data-out-prod/REGRESSION_TESTS/assignment/Backfill/MODELDATA/PREDICTIONS/trip_spend_predictions/trip_spend_predictions_2018-12-29.csv
      PRED_LIST: s3://memberanalytics-data-out-prod/REGRESSION_TESTS/assignment/Backfill/MODELDATA/PREDICTIONS/preds-20190215-combined_ah4_yt_April/PARQUET/
      FHH: s3://memberanalytics-data-out-prod/REGRESSION_TESTS/assignment/Backfill/ASSIGNMENTS/campaigns/campaign/input_mail_list
      MAIL_LIST: s3://memberanalytics-data-out-prod/REGRESSION_TESTS/assignment/Backfill/ASSIGNMENTS/campaigns/campaign/input_mail_list
      BACKTEST_MAIL_LIST: s3://memberanalytics-data-out-prod/REGRESSION_TESTS/assignment/Backfill/ASSIGNMENTS/campaigns/campaign/input_mail_list
      CPG_COUPON_LIST_PATH: s3://memberanalytics-data-out-prod/REGRESSION_TESTS/assignment/Backfill/ASSIGNMENTS/campaigns/campaign/input_coupon_list/article.csv
      CATEGORY_COUPON_PATH: s3://memberanalytics-data-out-prod/REGRESSION_TESTS/assignment/Backfill/ASSIGNMENTS/campaigns/campaign/input_coupon_list/category.csv
      BASKET_COUPON_PATH: s3://memberanalytics-data-out-prod/REGRESSION_TESTS/assignment/Backfill/ASSIGNMENTS/campaigns/campaign/input_coupon_list/basket.csv
      VERSION_MAP: s3://memberanalytics-data-out-prod/REGRESSION_TESTS/assignment/Backfill/ASSIGNMENTS/campaigns/campaign/input_version_map
      INPUT_ASSIGNMENTS: s3://memberanalytics-data-out-prod/REGRESSION_TESTS/assignment/Backfill/ASSIGNMENTS/cdsa/assn_output/backfill_mmpc/<sbrestin-10.13.48.32>/regression_test_2019-08-20/assignments
      INPUT_CONSTRUCTS: s3://memberanalytics-data-out-prod/REGRESSION_TESTS/assignment/Backfill/ASSIGNMENTS/cdsa/assn_output/backfill_mmpc/<sbrestin-10.13.48.32>/regression_test_2019-08-20/assignments_allconstructs
      INPUT_MAILHOUSE: null
      MAIL_POPULATION_ASSIGNMENT: s3://memberanalytics-data-out-prod/REGRESSION_TESTS/assignment/Backfill/ASSIGNMENTS/cdsa/assn_output/backfill_mmpc/<sbrestin-10.13.48.32>/regression_test_2019-08-20/mail_subset
      EXCLUSIONS: null
shared:
      experiment: 1
      campaign: backfill_mmpc
      run_name: regression_test
      run_type: test
      run_size: full
      assignment_date: '2019-08-20'
      sampling_weeks_rev_columns: LAST_TWENTY-SIX_WEEK_SPEND
      tmp_location: s3://memberanalytics-data-out-prod/work/tmp
coupon_creation:
      coupon_inhome_date: '2018-02-05'
      excluded_coupons_force_back_in: null
      backfill:
            cpn_exclusion:
            - null
            substitutable_MCH3_exclusion:
            - SUNDRIES
            - GENERAL MERCHANDISE
            cpn_force_in:
            - null
      coupon_types:
      - Paper Coupon
      - Clipless Coupon
      exclusion_types:
      - PURCHASE_CYCLE
      - INVENTORY
      hero_coupons:
      - null
      coupon_start_date: null
      coupon_end_date: null
assignment:
      replace_with_null: []
      downsample_coupons: null
      backfill_method:
            category: rank_by_agg_cf
            basket: hardest
            dummy: static
            article: rank_by_agg_trips
            article_hero: null
      backfill_priority: low
sizing:
      min_cpn_start_date: '2018-02-05'
      max_cpn_end_date: '2018-02-05'
      num_days_backwards: 364
      article_red_over_qual_rate: 0.37
      article_cann_rate: 0.8
      category_red_over_qual_rate: 0.25
      category_cann_rate: 0.5
      basket_red_over_qual_rate: 0.33
      basket_cann_rate: 0.6
      basket_sales_lift_per_capita: 1.1
subset:
      sample_size: 0
      force_in_new: true
      force_in_cells: null
      force_out_cells:
      error: 0
      max_decile_6: null
      sample_cells:
      - 1
qc:
      pre_configured:
            renewal:
                  include: false
                  group_by:
                  - cell_id
                  - version
                  - cpn_nbr
                  slot_nbr: []
            descriptive:
                  include: false
                  group_by:
                  - cell_id
                  - version
                  - cpn_nbr
                  slot_nbr: []
            personalized_content:
                  include: false
                  group_by:
                  - cell_id
                  - version
                  - cpn_nbr
                  slot_nbr: []
            savings_content:
                  include: false
                  version_letter:
                  - A
                  slot_content_map:
                        version_slot: 13
                        savings: 15
                        trips: 18
                        gas_trips: 20
                        top_category: 19
                        tenure: 21
                  group_by: []
                  slot_nbr: []
            compare:
                  group_by:
                  - cell_id
                  slot_nbr: []
      aggregation_params:
      -     coupon:
                  tab_names:
                  - cell-cpn-bfill
                  - cpn-slot-bfill
                  group_by:
                  -     - cell_id
                        - cpn_type
                        - is_backfill
                  -     - cpn_type
                        - slot_nbr
                        - is_backfill
                  aggs:
                  -     - '*'
                        - count
      -     more_coupon:
                  tab_names:
                  - cell-backfill
                  - cell-slot-backfill
                  group_by:
                  -     - cell_id
                        - is_backfill
                  -     - cell_id
                        - slot_nbr
                        - is_backfill
                  aggs:
                  -     - '*'
                        - count
      -     full:
                  tab_names:
                  - full
                  group_by:
                  -     - cell_id
                        - cpn_type
                        - slot_nbr
                        - is_backfill
                  aggs:
                  -     - '*'
                        - count
regression_test:
      creation:
            sample_members:
            - 57449291
            - 33193978
            - 15983197
            - 7582685
            - 32893974
            pct_fhh: 0.2
            article_coupons:
                  num_coupons: 10
            basket_coupons:
                  num_coupons: 5
            category_coupons:
                  num_coupons: 10
            csv_rows:
                  campaign.csv: 1
                  constructs.csv: 2
                  cells.csv: 1
                  segments.csv: 1
                  handshakes.csv: 1
                  msmt_cells.csv: 1
            output_partitions: 1
      execution: null
