detail:
  type: 'intermediate'
  path: 's3://memberanalytics-data-out-prod/pipelined_intermediates/transaction_fiscal/detail_isnr'
member:
  type: 'master'
  path: 's3://memberanalytics-data-out-prod/pipelined_intermediates/master/member'
item:
  type: 'master'
  path: 's3://memberanalytics-data-out-prod/AD_HOC/pipelined_intermediates/master/item_with_brand'
member_extended:
  type: 'master'
  path: 's3://memberanalytics-data-out-prod/pipelined_intermediates/master/member_extended'
exclusion:
  type: 'template'
  path: 's3://memberanalytics-data-out-prod/exclusions/exclusions_with_brand.csv'
out:
  type: 'out'
  path: 's3://memberanalytics-data-out-prod/CATEGORY_DNA/PROD/'
